# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='ifdirty',
            field=models.BooleanField(default=False),
        ),
    ]
