# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_commentmodel_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='votes',
            field=models.BooleanField(default=False),
        ),
    ]
